export const features = [
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "Think of us as your tech GPS—always pointing you in the right direction.",
        title: 'Software Development: Turning Ideas into Reality',
        description: 'From custom applications to enterprise-grade systems, we craft software solutions that meet your unique needs. Whether it’s a mobile app that wows users or an ERP system that streamlines workflows, we’ve got you covered.',
        checks: [
            'Custom Software Development',
            'Mobile App Development (iOS, Android, Cross-platform)',
            'Web Application Development',
            'SaaS Product Development',
            'API Development and Integration',
            'ERP/CRM Development',
            'E-commerce Platform Development',
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c67_Features%20Images%2003.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c63_Icon.svg',
        quote: "Think of us as your tech GPS—always pointing you in the right direction.",
        title: 'Cloud Services: Your Digital Foundation',
        description: 'Modern businesses run on the cloud—and so should yours. Whether it’s cloud migration, hosting, or scaling your infrastructure, we make it seamless and secure.',
        checks: [
            'Cloud Migration Services',
            'Cloud Application Development',
            'Cloud Storage and Backup Solutions',
            'Cloud Hosting and Server Management',
            'Cloud Security Solutions (e.g., AWS, Azure, GCP)',
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c63_Icon.svg',
        quote: "Think of us as your tech GPS—always pointing you in the right direction.",
        title: 'Cybersecurity: Sleep Tight, We’ve Got Your Back',
        description: 'Data breaches? Not on our watch. With industry-leading tools and practices, we keep your business safe from threats and ensure compliance with all regulations.',
        checks: [
            'Vulnerability Assessments and Penetration Testing',
            'Endpoint Security',
            'Firewall Configuration and Management',
            'Data Encryption Solutions',
            'Incident Response and Recovery',
            'Security Awareness Training for Employees',
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c6f_Features%20Images%2002.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "Think of us as your tech GPS—always pointing you in the right direction.",
        title: 'Data Solutions: Making Sense of the Chaos',
        description: 'Transform your data into actionable insights with our analytics and reporting services. From predictive models to dashboards, we help you see the bigger picture.',
        checks: [
            'Data Analytics and Reporting',
            'Business Intelligence Solutions',
            'Data Warehousing',
            'Big Data Solutions',
            'Data Migration Services',
            'ETL (Extract, Transform, Load) Services',
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c67_Features%20Images%2003.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c63_Icon.svg',
        quote: "Think of us as your tech GPS—always pointing you in the right direction.",
        title: 'AI and Machine Learning: The Future at Your Fingertips',
        description: 'From chatbots to advanced predictive models, we bring the power of AI to your business. Automate tasks, optimize processes, and deliver personalized customer experiences.',
        checks: [
            'AI Chatbot Development',
            'Predictive Analytics',
            'Machine Learning Model Training',
            'Natural Language Processing (NLP) Solutions',
            'Computer Vision Applications',
            'AI-powered Recommendation Systems',
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "Think of us as your tech GPS—always pointing you in the right direction.",
        title: 'Networking and Infrastructure: Built to Perform',
        description: 'From designing robust networks to maintaining seamless connectivity, we ensure your infrastructure is as reliable as your morning coffee.',
        checks: [
            'Network Design and Implementation',
            'Network Security Solutions',
            'Wireless Network Setup',
            'Virtual Private Network (VPN) Services',
            'Infrastructure Optimization and Scalability',
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c67_Features%20Images%2003.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c63_Icon.svg',
        quote: "Think of us as your tech GPS—always pointing you in the right direction.",
        title: 'DevOps: Faster, Smarter, Better',
        description: 'Optimize your development lifecycle with our DevOps services. We streamline CI/CD pipelines, enhance team collaboration, and accelerate time-to-market.',
        checks: [
            'Continuous Integration/Continuous Deployment (CI/CD)',
            'Infrastructure as Code (IaC)',
            'Containerization (Docker, Kubernetes)',
            'Monitoring and Performance Optimization',
            'DevOps Consulting',
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c6f_Features%20Images%2002.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "Think of us as your tech GPS—always pointing you in the right direction.",
        title: 'Automation: Let the Bots Do the Work',
        description: 'Why do it manually when it can be automated? From RPA to workflow automation, we help you eliminate inefficiencies and save precious time.',
        checks: [
            'Robotic Process Automation (RPA)',
            'Workflow Automation',
            'Custom Script Automation',
            'IT Process Automation',
            'Chatbot Integration for Automation',
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c67_Features%20Images%2003.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c63_Icon.svg',
        quote: "Think of us as your tech GPS—always pointing you in the right direction.",
        title: 'Digital Marketing: A Winning Online Strategy',
        description: 'From SEO to PPC campaigns, we help you build a digital presence that drives results. Whether it’s boosting visibility or generating leads, our team delivers.',
        checks: [
            'SEO and SEM Services',
            'Social Media Marketing',
            'Email Marketing Automation',
            'PPC Campaign Management',
            'Content Marketing Strategies',
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c63_Icon.svg',
        quote: "Think of us as your tech GPS—always pointing you in the right direction.",
        title: 'Digital Marketing: A Winning Online Strategy',
        description: 'From SEO to PPC campaigns, we help you build a digital presence that drives results. Whether it’s boosting visibility or generating leads, our team delivers.',
        checks: [
            'SEO and SEM Services',
            'Social Media Marketing',
            'Email Marketing Automation',
            'PPC Campaign Management',
            'Content Marketing Strategies',
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "We don’t just make ads; we make your competitors nervous.",
        title: "Blockchain Solutions: Trust Made Transparent",
        description: "Secure, transparent, and decentralized—that’s the power of blockchain. From smart contracts to supply chain solutions, we bring this revolutionary tech to your business.",
        checks: [
            "Smart Contract Development",
            "Cryptocurrency Wallet Development",
            "Decentralized Application (dApp) Development",
            "Blockchain Integration for Supply Chain",
            "Tokenization Services"
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "Buzzword? Maybe. Game-changer? Absolutely.",
        title: "IoT Solutions: Smart Tech for Smart Businesses",
        description: "Leverage IoT to connect devices and gather actionable insights. From smart homes to industrial IoT, we make the internet of things work for you.",
        checks: [
            "IoT Device Integration",
            "Smart Home Solutions",
            "Industrial IoT (IIoT)",
            "IoT Data Analytics",
            "IoT Security Solutions"
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "Because everything’s better when it’s connected.",
        title: "Communication and Collaboration Tools: Work Smarter, Together",
        description: "Empower your teams with cutting-edge tools like VoIP systems, video conferencing solutions, and team collaboration platforms. We help you stay connected, productive, and ready for action—no matter where your team is.",
        checks: [
            "VoIP Setup and Management",
            "Video Conferencing Solutions",
            "Collaboration Tools Deployment (e.g., Slack, Microsoft Teams)"
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "Bringing people together faster than you can say, ‘Can everyone hear me?’",
        title: "Game Development: Turning Play Into Profit",
        description: "From mobile games to immersive AR/VR experiences, we design and develop games that captivate audiences and drive engagement. Whether you’re building entertainment or gamifying your business, we’ve got the skills to level up.",
        checks: [
            "Mobile Game Development",
            "AR/VR Game Development",
            "Gamification for Businesses",
            "Multiplayer Game Servers"
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "We don’t just play games; we build them—and we’re pretty good at both.",
        title: "Compliance and Auditing: Stay Safe, Stay Legal",
        description: "Navigating complex regulations like GDPR, HIPAA, or PCI DSS? We’ve got you covered. From audits to compliance strategies, we ensure your business stays secure and aligned with global standards.",
        checks: [
            "GDPR, HIPAA, and PCI DSS Compliance",
            "IT Auditing Services",
            "Security Policy Development",
            "Risk Assessment and Management"
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "We make compliance a breeze, so you can save the sweating for the gym.",
        title: "SaaS and Marketplace Integration: Seamless Connections",
        description: "Streamline your operations with SaaS and marketplace integrations. From subscription management to third-party tools, we ensure everything works harmoniously—like an orchestra, minus the missed notes.",
        checks: [
            "Third-party SaaS Integration",
            "Marketplace Setup (Amazon, Shopify, etc.)",
            "Subscription Management Systems",
            "Payment Gateway Integration"
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "Think of us as the IT matchmakers—connecting tools, so you don’t have to.",
        title: "Augmented Reality (AR) and Virtual Reality (VR): Innovate in 3D",
        description: "Step into the future with AR and VR solutions tailored for training, marketing, and entertainment. We create immersive experiences that wow audiences and bring your ideas to life.",
        checks: [
            "AR App Development",
            "VR Training Simulations",
            "3D Modeling and Visualization",
            "Immersive Marketing Experiences"
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "We’re taking reality and upgrading it—no glitches included.",
        title: "IT Consulting: The Expertise You Can Trust",
        description: "Need a strategy to tackle your tech challenges? Our consultants bring decades of expertise to craft customized solutions for your business. From digital transformation to IT roadmaps, we’re here to guide the way.",
        checks: [
            "Digital Transformation Strategy",
            "IT Infrastructure Assessment",
            "Technology Roadmap Development",
            "Compliance and Risk Assessment",
            "IT Procurement and Vendor Management"
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "Think of us as your tech GPS—always pointing you in the right direction.",
        title: "IT Support and Maintenance: Always On, Always Ready",
        description: "Keep your systems running like clockwork with our comprehensive IT support and maintenance services. From troubleshooting to regular updates, we ensure your business never skips a beat.",
        checks: [
            "Managed IT Services",
            "Remote IT Support",
            "Infrastructure Management",
            "IT Helpdesk Services",
            "Network Monitoring and Troubleshooting"
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    },
    {
        icon: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c64_Icon-1.svg',
        quote: "Your tech problems? Consider them solved. You’re welcome.",
        title: "Website Development: Build Your Digital Home",
        description: "Your website is more than just a digital storefront—it’s your brand’s first impression. We design and develop websites that are fast, functional, and visually stunning, ensuring visitors stay and engage.",
        checks: [
            "Website Design and Development",
            "CMS Development (e.g., WordPress, Drupal)",
            "Landing Page Design",
            "Progressive Web App (PWA) Development",
            "Website Maintenance and Support"
        ],
        imageSrc: 'https://cdn.prod.website-files.com/66f30c8d2ac082d2aee64be2/66f30c8d2ac082d2aee64c66_Features%20Images%2001.jpg',
    }
];
